# Generated by Django 2.0 on 2018-03-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_to', models.TextField()),
                ('is_credit', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_ex_vat', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat_rate', models.DecimalField(choices=[(20.0, 'Standard 20%'), (0.0, 'Zero Rated')], decimal_places=2, max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='payments.Invoice')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('S', 'Stripe')], max_length=1)),
                ('status', models.CharField(choices=[('SUC', 'Successful'), ('FLD', 'Failed'), ('ERR', 'Errored'), ('RFD', 'Refunded'), ('CBK', 'Chargeback')], max_length=3)),
                ('charge_id', models.CharField(max_length=80)),
                ('charge_created', models.DateTimeField(null=True)),
                ('charge_failure_reason', models.CharField(blank=True, max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.Invoice')),
            ],
        ),
    ]
