# Generated by Django 2.0.2 on 2018-03-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0002_default_on_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicerow',
            unique_together={('invoice', 'object_type', 'object_id')},
        ),
    ]
