# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ironcage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(validators=[ironcage.validators.validate_max_300_words])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
