# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=20)),
                ('starter', models.CharField(blank=True, max_length=100, null=True)),
                ('main', models.CharField(blank=True, max_length=100, null=True)),
                ('pudding', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_charge_id', models.CharField(max_length=80, null=True)),
                ('stripe_charge_created', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
