sudo: false
language: python
cache: pip
python: 3.6
script: make test

notifications:
  email: false

install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: 9.6
