# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ironcage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('talk', 'A talk (25 minutes)'), ('workshop', 'A workshop (3 hours)'), ('poster', 'A poster'), ('other', 'Something else')], max_length=40)),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('copresenter_names', models.TextField(blank=True)),
                ('description', models.TextField(validators=[ironcage.validators.validate_max_300_words])),
                ('description_private', models.TextField(validators=[ironcage.validators.validate_max_300_words])),
                ('aimed_at_new_programmers', models.BooleanField()),
                ('aimed_at_teachers', models.BooleanField()),
                ('aimed_at_data_scientists', models.BooleanField()),
                ('would_like_mentor', models.BooleanField()),
                ('would_like_longer_slot', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
