# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_auto_20170811_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'permissions': [('review_proposal', 'Can review proposals')]},
        ),
    ]
