# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0003_auto_20170812_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
