# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0005_proposal_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='special_reply_required',
            field=models.BooleanField(default=False),
        ),
    ]
