# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0006_proposal_special_reply_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='scheduled_room',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='proposal',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
    ]
