# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_auto_20171011_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='info_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='slide_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
