# Generated by Django 2.0.2 on 2018-03-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20170827_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='fri',
            new_name='tue',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='thu',
            new_name='wed',
        ),
    ]
