# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170618_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessibility_reqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accessibility_reqs_yn',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='childcare_reqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='childcare_reqs_yn',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_reqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_reqs_yn',
            field=models.NullBooleanField(),
        ),
    ]
