# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_ukpa_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_booked_hotel',
            field=models.NullBooleanField(),
        ),
    ]
