# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 13:20
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_has_booked_hotel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.Manager()),
            ],
        ),
    ]
