# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170902_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_reg_desk',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_session_chair',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_setup',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_videoer',
            field=models.NullBooleanField(),
        ),
    ]
