# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171012_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
