# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coming_to_board_games',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='coming_to_dojo',
            field=models.NullBooleanField(),
        ),
    ]
