# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 21:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_name', models.CharField(max_length=255)),
                ('adult_email_addr', models.CharField(max_length=255)),
                ('adult_phone_number', models.CharField(max_length=255)),
                ('accessibility_reqs', models.TextField(blank=True, null=True)),
                ('dietary_reqs', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('stripe_charge_id', models.CharField(max_length=80)),
                ('stripe_charge_created', models.DateTimeField(null=True)),
                ('stripe_charge_failure_reason', models.CharField(blank=True, max_length=400)),
                ('unconfirmed_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='children.Order')),
            ],
        ),
    ]
