# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_charge_failure_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(default='ch_xyz', max_length=80),
            preserve_default=False,
        ),
    ]
