# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170521_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinvitation',
            name='status',
            field=models.CharField(default='unclaimed', max_length=10),
        ),
        migrations.AddField(
            model_name='ticketinvitation',
            name='token',
            field=models.CharField(default='0123456789ab', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
