# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_order_unconfirmed_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_charge_created',
            field=models.DateTimeField(null=True),
        ),
    ]
