# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_order_stripe_charge_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_addr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
