# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20170626_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Order'),
        ),
    ]
