# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20170903_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rate',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
