# Generated by Django 2.0.3 on 2018-03-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
