# Generated by Django 2.0.2 on 2018-03-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fri',
            new_name='tue',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='thu',
            new_name='wed',
        ),
    ]
