# Generated by Django 2.0.2 on 2018-03-31 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_change_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rate',
            field=models.CharField(choices=[('INDI', 'Individual'), ('CORP', 'Corporate'), ('EDUC', 'Educational'), ('FREE', 'Free')], max_length=4),
        ),
        migrations.AlterField(
            model_name='ticketinvitation',
            name='email_addr',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketinvitation',
            name='status',
            field=models.CharField(choices=[('U', 'Unclaimed'), ('C', 'Claimed')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticketinvitation',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='tickets.Ticket'),
        ),
    ]
